// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ymltraubfbpqfgnlofua.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InltbHRyYXViZmJwcWZnbmxvZnVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM4MTM4MjQsImV4cCI6MjA4OTM4OTgyNH0.JQ_KxhFCN-uesAIuNhuYBK3Wv1FnBzaoJM0P-89CYlI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});